name: debug

instance_groups:
  - name:      debug
    instances: 1
    azs:       [z1]

    vm_type:   default
    stemcell:  default

    networks:
      - name: default

    jobs:
      - name: debug
        release: debug
        properties:
          properties:
            foo: bar
            bar: baz

update:
  canaries: 0
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

releases:
- name:    debug
  version: latest
  #url:     ...
  #sha1:    ...
